spring.application.name=schedula

# 5432 Driver class name (often not strictly needed if the URL is correct, but good practice)
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/SchedulaDB
spring.datasource.username=postgres
spring.datasource.password=781135350
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
# إظهار استعلامات SQL للتأكد من العمل (اختياري للتجربة)
# spring.jpa.show-sql=true

# تحديد اسم الملف ومكانه
# logging.file.name=logs/app-main.log

# أو تحديد مسار فقط وسيقوم سبرينج بتسمية الملف spring.log
logging.file.path=logs/

# التحكم في مستويات التدوين لمسارات معينة
logging.level.com.schedula=DEBUG
logging.level.org.springframework=INFO

#تتيح للتطبيق معالجة آلاف الطلبات المتزامنة بذاكرة قليلة جداً.
spring.threads.virtual.enabled=true

#بروتوكول HTTP/2 أسرع بكثير من HTTP/1.1 لأنه يرسل عدة طلبات عبر اتصال واحد (Multiplexing)
server.http2.enabled=true

server.compression.enabled=true
server.compression.min-response-size=1024
spring.main.allow-bean-definition-overriding=false
spring.datasource.hikari.connection-timeout=20000 
# 20 ثانية

security.jwt.secret-key=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
# 1h in millisecond
app.jwt.expiration-in-ms=3600000
app.jwt.remember-me-expiration-in-ms=2592000000

app.frontend.url=http://localhost:4200