spring.application.name=schedula

# 5432 Driver class name (often not strictly needed if the URL is correct, but good practice)
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=${DDL_AUTO}


logging.file.path=logs/

# التحكم في مستويات التدوين لمسارات معينة
logging.level.com.schedula=DEBUG
logging.level.org.springframework=INFO

#تتيح للتطبيق معالجة آلاف الطلبات المتزامنة بذاكرة قليلة جداً.
spring.threads.virtual.enabled=true

#بروتوكول HTTP/2 أسرع بكثير من HTTP/1.1 لأنه يرسل عدة طلبات عبر اتصال واحد (Multiplexing)
server.http2.enabled=true

server.compression.enabled=true
server.compression.min-response-size=1024
spring.main.allow-bean-definition-overriding=false

security.jwt.secret-key=${JWT_SECRET_KEY}
# 1h in millisecond
app.jwt.expiration-in-ms=${JWT_EXPIRATION_IN_MS}
app.jwt.remember-me-expiration-in-ms=${JWT_REMEMBER_ME_EXPIRATION_IN_MS}

app.frontend.url=${FRONTEND_URL}

# تفعيل التجميع
spring.jpa.properties.hibernate.jdbc.batch_size=20
# تحسين الترتيب لزيادة كفاءة التجميع
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
# ميزة خاصة بـ PostgreSQL لدمج الطلبات
spring.datasource.hikari.data-source-properties.reWriteBatchedInserts=true

spring.datasource.hikari.maximum-pool-size=50

# spring.datasource.hikari.connection-timeout=30000
# TODO اذا كان هناك لها استخدام مستقبلاً وإلا تحذف
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}

# تعطيل Redis Repositories
spring.data.redis.repositories.enabled=false

# تعطيل Open Session In View
spring.jpa.open-in-view=false
# اختياري: إذا كان لديك كلمة مرور لـ Redis
spring.data.redis.password=${REDIS_PASSWORD:}

# إضافة وسم (Tag) عام لكل المقاييس لتمييز هذا التطبيق
management.metrics.tags.application=MySpringBootApp

# اختياري: تمكين إرسال المقاييس بتنسيق يتوافق مع Prometheus
management.prometheus.metrics.export.enabled=true

# تحديد ما يتم عرضه من تفاصيل نقطة نهاية Health
management.endpoint.health.show-details=when-authorized
management.endpoints.web.exposure.include=health,info,metrics,prometheus

server.servlet.session.cookie.same-site=${SAME_SITE}
